os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000 WFVERSION=11.0.0.Final
  - ARCH=armhf  PUID=1001 PGID=1001 WFVERSION=11.0.0.Final
  global:
  - secure: Aq8utwReNciMuUsxEFDiDJNYzot5rZhwoXoHqxcRnSyf8A+mk8ZlPorZ6zJ7F3UPRBjVnsYjT+lmZC8/faxRGL1FUbMIGqk7HQ48EoQp+yExoCZBfDaVaSx9ZOMpnFWQA6N/3//nG5xcMNgpZnJYP/aNoIa6ithtuaeRuLQewcJnXMHBK9wNa2w4DkjpAQutLltmR0gUNBAkz8TGCZaSZhwJl42E6STpTHMa/lH3N7a4eLC7YJm8/hbyYukN966Gm4VooTU1Tuk8EchLo2c0lAs9nbarvHSRKpPNx4dyAtuTaCorzDwYWMtOPb3BEvt9Ys4fajJ1F187uo8XsJbRVkZIWn5aaF8vzE+zylYUbl4y+8/CcFNGq79A2pl7l2H36iQN01DHspwdibXDtp24DAM7G3vxzCb+syvt6+Q7Kxhs8EP+aKgWzLIIRpvLPpO2kVXoAX68HYOy/ttA8fuF6FHWSEPvRu7CnGWWC3OGlLYexgjfM7gKWcwhM90rgiB99GkPb4/AVVabR5MY3U+AjHTGSApeibMqCDxzLFTqM+jFH4CQcGamq6JnuZAP55GZOBh8HSt7pBTsJ1sck+flOi7R0bYltPenDIe9j+vqIzl1sTj3OkwjUWf9Rm169a3/2C0L9fNmGJZ7DUSqIP5Us/CMJdq8oK7MG/HrlQmWlLc=
  - secure: n/8Mp6zAKPdECoakyXCFPeUUHwg+WqferbGmBLC/7Ad03ng9Y5At09qum1N7uB/5voYnzXjZecXA4dHLTHC+RyONJ6XhtxlXdT/OrcckiafYZ+eePn2O5TeFBejZRko7ST7o5jKSbb0dWsW+i4Fvx3Y+3rFLLNYyeLt8Qy3C6IfFViM6w/3B/KE+Og//zLHhZYa9L0cNUYVFyV91cSnuFqa779FBwcNw6nF7rXk7vzOYPDDnzNzl8Zln0QdPP5Db17ny+6zILhT+l0J4s3ZQf9Y6aqC/UfpOyUxGowwX304gLAVuHXKSgJKyVUOAZmegw1SJtKvWdcac39GOjli/6g9dYUSV0Q0o2Vg+2NdWjkAPXhU0CWRmBxr9QBUHEhIhoQe+CU0OP7XWWOnP8Ks8VC5WaBlmXsItqGOCbXNIfacR/zj4amequT+t2vmYPFLvjXVBtVxKhrhKhNc1EKUTxHufe6ajTDC4oW+tKjO4FGER//zyvBwEslnrXFEPjFF5xxssI1Y2B+Nc/ZSDG3WcyaSGkvncAo2v5YR32Nev2ZXWc1ABhXYLSujZXs1XyqW57zctDMSoKlBQWEB7kU4cQCznREEi2fweEC+lPCMHNgnPKV3/Lq6W7RLagEvGLgSIJtnvVpV5aJ96bTedX9uK63wkAr+FGRx1BPMtL11EGpk=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} WFVERSION=${WFVERSION}
  build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
